safe:        false
port:        4000
base-url:    /

source:      .
destination: ./_site
plugins_dir: ./_plugins

future:      true
lsi:         false
highlighter: pygments
markdown:    kramdown
permalink:   date

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  syntax_highlighter_opts:
    wrap: div
    line_numbers: inline
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: style

exclude: [ Gemfile, Gemfile.lock, Procfile, vendor ]